name: Multitask_RealOnly

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    robot0_agentview_right_image:
      shape: [3, 256, 256]
      type: rgb
      lerobot_keys: ['video.robot0_agentview_right']
    robot0_agentview_left_image:
      shape: [3, 256, 256]
      type: rgb
      lerobot_keys: ['video.robot0_agentview_left']
    robot0_eye_in_hand_image:
      shape: [3, 256, 256]
      type: rgb
      lerobot_keys: ['video.robot0_eye_in_hand']
    robot0_base_to_eef_pos:
      shape: [3]
      lerobot_keys: ['state.end_effector_position_relative']
    robot0_base_to_eef_quat:
      shape: [4]
      lerobot_keys: ['state.end_effector_rotation_relative']
    robot0_gripper_qpos:
      shape: [2]
      lerobot_keys: ['state.gripper_qpos']
    lang_emb:
      shape: [768]
  action: 
    shape: [12]
    lerobot_keys: ['action.end_effector_position', 'action.end_effector_rotation', 'action.gripper_close', 'action.base_motion', 'action.control_mode',]

abs_action: &abs_action False

env_runner:
  _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
  dataset_path: /mnt/amlfs-01/shared/robocasa_benchmark/robocasa-datasets/v0.5/test/atomic/PnPCounterToCabinet/20250811/demo.hdf5
  shape_meta: *shape_meta
  # costs 1GB per env
  n_train: 0
  n_train_vis: 1
  train_start_idx: 0
  n_test: 50
  n_test_vis: 4
  test_start_seed: 100000
  max_steps: 600
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  render_obs_key: 'robot0_agentview_right_image'
  fps: 10
  crf: 22
  past_action: ${past_action_visible}
  abs_action: *abs_action
  tqdm_interval_sec: 1.0
  n_envs: 1
  env_kwargs:
    seed: 1111111
    obj_instance_split: 'test'
    style_ids: null
    layout_ids: null
    layout_and_style_ids: [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]]
    clutter_mode: 1

    use_camera_obs: true
    use_object_obs: true
    camera_depths: false
    has_renderer: false
    has_offscreen_renderer: true
    camera_names: ['robot0_agentview_left', 'robot0_agentview_right', 'robot0_eye_in_hand']
    camera_widths: 256
    camera_heights: 256
    ignore_done: true
    reward_shaping: false
# evaluation at this config requires a 16 core 64GB instance.

dataset:
  _target_: diffusion_policy.dataset.lerobot_dataset.LerobotCotrainingDataset
  shape_meta: *shape_meta
  dataset_soup: real_multitask_realonly
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  seed: 42
  val_ratio: 0.02